name: Test

on: [push, pull_request]

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2

      - name: Run ci
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --without docs
          make ci
