name: CI

on: [push, pull_request]

jobs:
  test-code:
    name : test ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3

      - name: Run ci
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --without docs
          make ci
